import type { BrowseMemory } from "./browse-data";

export const browseFixtureMemories: BrowseMemory[] = [
  {
    id: "memory-foundation",
    title: "Reader Mode Notes",
    url: "https://example.com/reader-mode/source/with/a/very/long/path/that/should/remain/on/one/line?encoded=%E3%81%82%E3%81%AA%E3%81%9F%E3%81%AE%E4%BB%95%E4%BA%8B%E3%81%AF%E5%8B%95%E4%BD%9C%E3%81%99%E3%82%8B%E3%82%B3%E3%83%BC%E3%83%89",
    description: "SolidStart route data and shell architecture notes for the canonical reader.",
    capturedAt: "2026-05-09",
    read: false,
    extractionStatus: "success",
    categories: [{ id: "research", name: "Research" }],
    tags: [
      { id: "solidstart", name: "solidstart" },
      { id: "reader", name: "reader" },
    ],
    flashbacks: [
      {
        id: "h-foundation",
        memoryId: "memory-foundation",
        variantKind: "source",
        langCode: null,
        translationOutputHash: null,
        text: "flashback-aware results",
        prefix: "Search query can be wired to",
        suffix: "through repository fixtures.",
        createdAt: "2026-05-09T12:00:00.000Z",
      },
    ],
  },
  {
    id: "memory-ops",
    title: "Local Hosting Checklist",
    url: "https://example.com/local-hosting",
    description: "Single Bun process and persistent disk assumptions for self-hosted operation.",
    capturedAt: "2026-05-08",
    read: false,
    extractionStatus: "success",
    categories: [{ id: "operations", name: "Operations" }],
    tags: [
      { id: "sqlite", name: "sqlite" },
      { id: "backup", name: "backup" },
    ],
    flashbacks: [
      {
        id: "h-ops",
        memoryId: "memory-ops",
        variantKind: "source",
        langCode: null,
        translationOutputHash: null,
        text: "persistent disk assumptions",
        prefix: "The app keeps deployment simple with",
        suffix: "and a markdown store.",
        createdAt: "2026-05-08T12:00:00.000Z",
      },
    ],
  },
  {
    id: "memory-design",
    title: "Browse Shell Sketch",
    url: "https://example.com/browse-shell",
    description: "X-like layout notes for navigation, filters, and dense memory browsing.",
    capturedAt: "2026-05-07",
    read: false,
    extractionStatus: "success",
    categories: [{ id: "product", name: "Product" }],
    tags: [
      { id: "shell", name: "shell" },
      { id: "filters", name: "filters" },
    ],
    flashbacks: [
      {
        id: "h-shell",
        memoryId: "memory-design",
        variantKind: "source",
        langCode: null,
        translationOutputHash: null,
        text: "right filter panel updates URL state",
        prefix: "The canonical browse workflow requires that the",
        suffix: "without page-local navigation.",
        createdAt: "2026-05-07T12:00:00.000Z",
      },
    ],
  },
  {
    id: "memory-no-flashbacks",
    title: "Archive Import Runbook",
    url: "https://example.com/archive-import",
    description: "Operational notes for adding a memory that has no saved flashbacks yet.",
    capturedAt: "2026-05-06",
    read: false,
    extractionStatus: "link_only",
    categories: [{ id: "operations", name: "Operations" }],
    tags: [
      { id: "import", name: "import" },
      { id: "runbook", name: "runbook" },
    ],
    flashbacks: [],
  },
];
